sudo: required
services:
  - docker

before_install:
  - docker build -t kjfontaine/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kjfontaine/docker-react npm run test -- --coverage
